# Generated by Django 4.2.4 on 2025-04-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymmediaupload',
            name='author',
        ),
        migrations.AlterField(
            model_name='gymitem',
            name='equipment',
            field=models.CharField(blank=True, choices=[('bands', 'Elastici'), ('barbell', 'Bilanciere'), ('body only', 'Corpo Libero'), ('cable', 'Cavi'), ('dumbbell', 'Manubri'), ('e-z curl bar', 'Bilanciere E-Z'), ('exercise ball', 'Palla Fitness'), ('foam roll', 'Rullo di Schiuma'), ('kettlebells', 'Kettlebell'), ('machine', 'Macchinario'), ('medicine ball', 'Palla Medica'), ('other', 'Altro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gymitem',
            name='force',
            field=models.CharField(blank=True, choices=[('pull', 'Pull'), ('push', 'Push'), ('static', 'Statico')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gymitem',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('expert', 'Esperto')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gymitem',
            name='mechanic',
            field=models.CharField(blank=True, choices=[('compound', 'Multiarticolare'), ('isolation', 'Isolamento')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gymitem',
            name='primary_muscle',
            field=models.CharField(blank=True, choices=[('abdominals', 'Addominali'), ('abductors', 'Abduttori'), ('adductors', 'Adduttori'), ('biceps', 'Bicipiti'), ('calves', 'Polpacci'), ('chest', 'Petto'), ('forearms', 'Avambracci'), ('glutes', 'Glutei'), ('hamstrings', 'Femorali'), ('lats', 'Dorsali'), ('lower back', 'Zona Lombare'), ('middle back', 'Schiena Media'), ('neck', 'Collo'), ('quadriceps', 'Quadricipiti'), ('shoulders', 'Spalle'), ('traps', 'Trapezi'), ('triceps', 'Tricipiti')], max_length=50, null=True),
        ),
    ]
