# Generated by Django 4.2.4 on 2025-04-14 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_gymplanitem_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymplansetdetail',
            name='plan_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='data.gymplanitem'),
        ),
    ]
