# Generated by Django 4.2.4 on 2025-04-11 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_gymmediaupload_author_alter_gymitem_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymplan',
            name='gym_items',
        ),
        migrations.RemoveField(
            model_name='gymplanitem',
            name='gym_plan',
        ),
        migrations.AddField(
            model_name='gymplansection',
            name='gym_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.gymplan'),
        ),
    ]
