# Generated by Django 4.2.4 on 2025-04-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_gymplan_gym_items_remove_gymplanitem_gym_plan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymplanitem',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='gymplansetdetail',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='gymplansetdetail',
            old_name='reps',
            new_name='prescribed_reps',
        ),
        migrations.RemoveField(
            model_name='gymplanitem',
            name='is_top_set',
        ),
        migrations.RemoveField(
            model_name='gymplanitem',
            name='rest_seconds',
        ),
        migrations.RemoveField(
            model_name='gymplanitem',
            name='rir',
        ),
        migrations.RemoveField(
            model_name='gymplanitem',
            name='series_type',
        ),
        migrations.RemoveField(
            model_name='gymplanitem',
            name='set_details',
        ),
        migrations.RemoveField(
            model_name='gymplanitem',
            name='target_range',
        ),
        migrations.RemoveField(
            model_name='gymplanitem',
            name='tempo_code',
        ),
        migrations.RemoveField(
            model_name='gymplanitem',
            name='weekly_progression',
        ),
        migrations.RemoveField(
            model_name='gymplansetdetail',
            name='set_type',
        ),
        migrations.RemoveField(
            model_name='gymplansetdetail',
            name='tempo_code',
        ),
        migrations.AddField(
            model_name='gymplansetdetail',
            name='actual_reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymplansetdetail',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordine del set nella lista'),
        ),
        migrations.AddField(
            model_name='gymplansetdetail',
            name='plan_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='data.gymplanitem'),
        ),
        migrations.AddField(
            model_name='gymplansetdetail',
            name='rest_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymplansetdetail',
            name='tempo',
            field=models.CharField(blank=True, help_text="Formato: 'eccentrica-pausa-concentrica', es. '3-1-2'", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gymplanitem',
            name='intensity_techniques',
            field=models.JSONField(blank=True, default=list, help_text="Lista di tecniche d’intensità (es: ['drop_set', 'tempo'])"),
        ),
        migrations.AlterField(
            model_name='gymplanitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gymplanitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gymplansetdetail',
            name='rir',
            field=models.PositiveIntegerField(blank=True, help_text='Reps in reserve', null=True),
        ),
        migrations.AlterField(
            model_name='gymplansetdetail',
            name='weight',
            field=models.FloatField(blank=True, help_text='Peso in kg', null=True),
        ),
    ]
