# Generated by Django 4.2.4 on 2025-04-14 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_gymplansetdetail_plan_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymplanitem',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.gymplan'),
        ),
    ]
