# Generated by Django 4.2.4 on 2025-04-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_gymplanitem_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymplanitem',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.gymitem'),
        ),
    ]
