# Generated by Django 4.2.4 on 2025-04-14 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_gymplanitem_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymplanitem',
            name='exercise',
        ),
        migrations.AddField(
            model_name='gymplansetdetail',
            name='exercise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data.gymitem'),
        ),
    ]
