# Generated by Django 4.2.4 on 2025-04-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_gymplanitem_exercise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymplansetdetail',
            old_name='tempo',
            new_name='tempo_fcr',
        ),
    ]
