# Generated by Django 4.2.4 on 2025-05-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_rename_actual_reps_gymplansetdetail_actual_reps_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymplansection',
            name='type',
            field=models.CharField(blank=True, help_text='Es. Push, Gambe, Full Body', max_length=100),
        ),
        migrations.AlterField(
            model_name='gymplansetdetail',
            name='actual_reps_1',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gymplansetdetail',
            name='prescribed_reps_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gymplansetdetail',
            name='rest_seconds',
            field=models.PositiveIntegerField(blank=True, default=60, null=True),
        ),
        migrations.AlterField(
            model_name='gymplansetdetail',
            name='rir',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Reps in reserve', null=True),
        ),
        migrations.AlterField(
            model_name='gymplansetdetail',
            name='tempo_fcr',
            field=models.CharField(blank=True, default='0-0-0', help_text="Formato: 'eccentrica-pausa-concentrica', es. '3-1-2'", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gymplansetdetail',
            name='weight',
            field=models.FloatField(blank=True, default=0, help_text='Peso in kg', null=True),
        ),
    ]
