# Generated by Django 5.2 on 2025-05-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_gymplansection_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsaccount',
            name='goal_description',
            field=models.CharField(blank=True, default='', help_text='Descrivi brevemente il tuo obiettivo (max 160 caratteri)', max_length=160),
        ),
        migrations.AddField(
            model_name='detailsaccount',
            name='goal_targets',
            field=models.CharField(blank=True, choices=[('fitness', 'Fitness'), ('bodybuilding', 'Bodybuilding'), ('powerlifting', 'Powerlifting'), ('streetlifting', 'Streetlifting')], default=['fitness']),
        ),
    ]
