# Generated by Django 5.2 on 2025-05-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_detailsaccount_goal_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsaccount',
            name='goal_targets_explanation',
            field=models.TextField(blank=True, help_text="Spiegazione generata dall'IA sul perché è stato selezionato questo obiettivo."),
        ),
        migrations.AlterField(
            model_name='detailsaccount',
            name='goal_targets',
            field=models.CharField(blank=True, choices=[('fitness', 'Fitness'), ('bodybuilding', 'Bodybuilding'), ('powerlifting', 'Powerlifting'), ('streetlifting', 'Streetlifting')]),
        ),
    ]
